// Traits de visage et proportions, par espèce.
// Tout est facultatif : sans entrée, le générateur applique les valeurs par
// défaut de la silhouette (voir FACE_DEFAULT dans gen-pokedex.mjs).
//   eyes  : round | beady | sharp | sleepy | blank | slit
//   mouth : none | smile | fangs | beak | grin
//   eye   : couleur de l'iris        eyeScale : taille des yeux
//   head  : taille de la tête        legs     : longueur des pattes
export default {
  /* --- regards durs : prédateurs, dragons, colosses --- */
  charmeleon: 'eyes:sharp mouth:fangs',
  charizard: 'eyes:sharp mouth:fangs head:.9',
  gyarados: 'eyes:sharp mouth:fangs head:1.3 eye:#e8544f',
  arbok: 'eyes:slit mouth:fangs eye:#e8544f',
  ekans: 'eyes:slit mouth:fangs eye:#f0d05a',
  houndour: 'eyes:sharp mouth:fangs eye:#e8544f',
  houndoom: 'eyes:sharp mouth:fangs eye:#e8544f head:.95',
  sneasel: 'eyes:sharp mouth:fangs eye:#e8544f',
  luxray: 'eyes:sharp mouth:fangs eye:#f0d05a',
  incineroar: 'eyes:sharp mouth:fangs eye:#f0d05a',
  tyranitar: 'eyes:sharp mouth:fangs head:.9',
  larvitar: 'eyes:sharp mouth:none',
  aggron: 'eyes:sharp mouth:fangs head:.85',
  lairon: 'eyes:sharp mouth:none head:.9',
  machamp: 'eyes:sharp mouth:none head:.8',
  machoke: 'eyes:sharp mouth:none head:.85',
  machop: 'eyes:round mouth:none head:.9',
  blaziken: 'eyes:sharp mouth:beak legs:1.25',
  combusken: 'eyes:sharp mouth:beak legs:1.15',
  feraligatr: 'eyes:sharp mouth:fangs',
  croconaw: 'eyes:round mouth:fangs',
  totodile: 'eyes:round mouth:fangs',
  sceptile: 'eyes:sharp mouth:none legs:1.1',
  greninja: 'eyes:sharp mouth:none eye:#f0d05a',
  meowscarada: 'eyes:sharp mouth:smile eye:#5fbf8f',
  staraptor: 'eyes:sharp mouth:beak legs:1.2',
  skarmory: 'eyes:sharp mouth:beak',
  salamence: 'eyes:sharp mouth:fangs',
  garchomp: 'eyes:sharp mouth:fangs eye:#f0d05a',
  gabite: 'eyes:sharp mouth:fangs',
  haxorus: 'eyes:sharp mouth:fangs eye:#e8544f',
  fraxure: 'eyes:sharp mouth:fangs',
  hydreigon: 'eyes:blank mouth:fangs eye:#e8544f',
  zweilous: 'eyes:blank mouth:fangs',
  deino: 'eyes:blank mouth:fangs',
  'kommo-o': 'eyes:sharp mouth:fangs',
  zekrom: 'eyes:sharp mouth:fangs eye:#5fb0ff',
  koraidon: 'eyes:sharp mouth:fangs eye:#5fbfc8',
  rayquaza: 'eyes:slit mouth:fangs eye:#f0d05a head:.85',
  beartic: 'eyes:sharp mouth:fangs',
  mamoswine: 'eyes:sharp mouth:fangs head:.85',

  /* --- regards vides : spectres, machines, légendaires --- */
  gastly: 'eyes:blank mouth:grin eye:#e8544f eyeScale:1.2',
  haunter: 'eyes:blank mouth:grin eye:#e8544f eyeScale:1.15',
  gengar: 'eyes:blank mouth:grin eye:#e8544f',
  mimikyu: 'eyes:blank mouth:none eye:#3a3d4a',
  darkrai: 'eyes:blank mouth:none eye:#7fd0ff',
  dreepy: 'eyes:blank mouth:none eye:#e8804f',
  drakloak: 'eyes:blank mouth:none eye:#e8804f',
  dragapult: 'eyes:blank mouth:fangs eye:#e8804f',
  magnemite: 'eyes:blank mouth:none eyeScale:1.6',
  magneton: 'eyes:blank mouth:none eyeScale:1.4',
  magnezone: 'eyes:blank mouth:none eyeScale:1.3',
  mewtwo: 'eyes:blank mouth:none eye:#9a7fb8 head:1.1',
  lugia: 'eyes:sharp mouth:beak eye:#5fb0ff',
  xerneas: 'eyes:blank mouth:none eye:#5fbfc8',
  zacian: 'eyes:sharp mouth:fangs eye:#e8544f',

  /* --- regards mi-clos : lourds et placides --- */
  snorlax: 'eyes:sleepy mouth:smile head:.8',
  swinub: 'eyes:sleepy mouth:none',
  piloswine: 'eyes:sleepy mouth:fangs',
  hippopotas: 'eyes:sleepy mouth:none',
  hippowdon: 'eyes:sleepy mouth:fangs head:.9',
  metapod: 'eyes:sleepy mouth:none',
  shelgon: 'eyes:sleepy mouth:none',
  koffing: 'eyes:sleepy mouth:grin',
  weezing: 'eyes:sleepy mouth:grin',

  /* --- pupilles fendues : serpents et reptiles --- */
  dratini: 'eyes:slit mouth:none',
  dragonair: 'eyes:slit mouth:none',
  onix: 'eyes:sharp mouth:none head:.65',
  steelix: 'eyes:sharp mouth:fangs head:.65',
  snivy: 'eyes:slit mouth:smile',
  servine: 'eyes:slit mouth:smile',
  serperior: 'eyes:slit mouth:none eye:#e8544f',
  salandit: 'eyes:slit mouth:fangs',
  salazzle: 'eyes:slit mouth:fangs eye:#e8544f',

  /* --- petits yeux ronds : bestioles et oiseaux --- */
  caterpie: 'eyes:beady mouth:none',
  pidgey: 'eyes:beady mouth:beak',
  rattata: 'eyes:beady mouth:fangs',
  raticate: 'eyes:beady mouth:fangs',
  diglett: 'eyes:beady mouth:smile',
  dugtrio: 'eyes:beady mouth:smile',
  magikarp: 'eyes:beady mouth:none eyeScale:1.3',
  zubat: 'eyes:blank mouth:fangs',
  golbat: 'eyes:sharp mouth:grin',

  /* --- bouilles amicales --- */
  bulbasaur: 'eyes:round mouth:smile',
  ivysaur: 'eyes:round mouth:smile',
  venusaur: 'eyes:sharp mouth:fangs head:.9',
  squirtle: 'eyes:round mouth:smile',
  wartortle: 'eyes:round mouth:smile',
  blastoise: 'eyes:sharp mouth:none head:.9',
  pikachu: 'eyes:round mouth:smile eyeScale:1.15',
  raichu: 'eyes:round mouth:smile',
  pawmi: 'eyes:round mouth:smile eyeScale:1.15',
  eevee: 'eyes:round mouth:smile eyeScale:1.2',
  vaporeon: 'eyes:round mouth:smile',
  jolteon: 'eyes:sharp mouth:none',
  flareon: 'eyes:round mouth:smile',
  espeon: 'eyes:round mouth:none eye:#8f5fa8',
  umbreon: 'eyes:round mouth:none eye:#e8544f',
  sylveon: 'eyes:round mouth:smile eye:#5fb0e0',
  clefairy: 'eyes:round mouth:smile eyeScale:1.15',
  clefable: 'eyes:round mouth:smile',
  togepi: 'eyes:round mouth:smile eyeScale:1.25',
  togetic: 'eyes:round mouth:smile',
  togekiss: 'eyes:round mouth:beak',
  chikorita: 'eyes:round mouth:smile',
  bayleef: 'eyes:round mouth:smile',
  meganium: 'eyes:round mouth:smile',
  mudkip: 'eyes:round mouth:smile eyeScale:1.15',
  marshtomp: 'eyes:round mouth:smile',
  swampert: 'eyes:sharp mouth:none',
  popplio: 'eyes:round mouth:smile eyeScale:1.2',
  brionne: 'eyes:round mouth:smile',
  primarina: 'eyes:round mouth:smile',
  turtwig: 'eyes:round mouth:smile',
  grotle: 'eyes:round mouth:smile',
  torterra: 'eyes:sharp mouth:none head:.85',
  lapras: 'eyes:round mouth:smile',
  chespin: 'eyes:round mouth:smile',
  fennekin: 'eyes:round mouth:smile',
  litten: 'eyes:sharp mouth:none',
  scorbunny: 'eyes:round mouth:smile legs:1.15',
  sobble: 'eyes:round mouth:none eyeScale:1.25',
  sprigatito: 'eyes:round mouth:smile',
  fuecoco: 'eyes:round mouth:smile eyeScale:1.2',
  quaxly: 'eyes:round mouth:beak',
  grookey: 'eyes:round mouth:smile',
  cyndaquil: 'eyes:sleepy mouth:none',
  quilava: 'eyes:sleepy mouth:none',
  typhlosion: 'eyes:sharp mouth:fangs',

  /* --- psychiques : tête plus grosse --- */
  abra: 'eyes:sleepy mouth:none head:1.1',
  kadabra: 'eyes:sharp mouth:none head:1.1',
  alakazam: 'eyes:sharp mouth:none head:1.15',
  ralts: 'eyes:blank mouth:none head:1.2',
  kirlia: 'eyes:round mouth:none head:1.1',
  gardevoir: 'eyes:round mouth:none eye:#e8544f',
};
